import './globals.css';
import '@radix-ui/themes/styles.css';
import { Theme } from "@radix-ui/themes";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Navbar'
const inter = Inter({ subsets: ['latin'], variable: "--font-inter" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme 
        appearance='light'
        accentColor='violet'
        style={{
          '--default-font-family': 'var(--font-inter)',
        } as React.CSSProperties}
        >
          <Navbar/>
          <main className='p-5'>{children}</main>
        </Theme>
      </body>
    </html>
  )
}
